
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIAGONAL = 16;
  public static final int BORRAR_PAGINA = 20;
  public static final int ALINEACION = 34;
  public static final int PAGINA = 32;
  public static final int PARAMETROS = 6;
  public static final int ANGULAR_ABIERTO = 2;
  public static final int CORCHETE_CERRADO = 55;
  public static final int NOMBRE = 8;
  public static final int ANCHO = 39;
  public static final int NUMEROS = 44;
  public static final int IZQUIERDA = 47;
  public static final int VIDEO = 52;
  public static final int ETIQUETAS = 11;
  public static final int FECHA = 56;
  public static final int MENU = 53;
  public static final int IGUAL = 14;
  public static final int CENTRAR = 48;
  public static final int TITULO = 30;
  public static final int PADRE = 40;
  public static final int ID = 25;
  public static final int NUEVA_PAGINA = 19;
  public static final int CORCHETE_ABIERTO = 41;
  public static final int EOF = 0;
  public static final int BORRAR_COMPONENTE = 23;
  public static final int CLASE = 33;
  public static final int error = 1;
  public static final int COMILLA = 15;
  public static final int PIPE = 45;
  public static final int FECHA_MODIFICACION = 28;
  public static final int URL = 54;
  public static final int ATRIBUTOS = 9;
  public static final int BORRAR_SITIO_WEB = 18;
  public static final int IDD = 42;
  public static final int ATRIBUTO = 10;
  public static final int ACCION = 5;
  public static final int COLOR = 36;
  public static final int USUARIO_MODIFICACION = 29;
  public static final int FECHA_CREACION = 27;
  public static final int NUEVO_SITIO_WEB = 17;
  public static final int USUARIO_CREACION = 26;
  public static final int VALOR = 13;
  public static final int ANGULAR_CERRADO = 3;
  public static final int IMAGEN = 51;
  public static final int DERECHA = 46;
  public static final int PARRAFO = 50;
  public static final int ORIGEN = 37;
  public static final int MODIFICAR_COMPONENTE = 24;
  public static final int AGREGAR_COMPONENTE = 22;
  public static final int HEXADECIMAL = 43;
  public static final int PARAMETRO = 7;
  public static final int ACCIONES = 4;
  public static final int SITIO = 31;
  public static final int TEXTO = 35;
  public static final int ETIQUETA = 12;
  public static final int JUSTIFICAR = 49;
  public static final int ALTURA = 38;
  public static final int MODIFICAR_PAGINA = 21;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ANGULAR_ABIERTO",
  "ANGULAR_CERRADO",
  "ACCIONES",
  "ACCION",
  "PARAMETROS",
  "PARAMETRO",
  "NOMBRE",
  "ATRIBUTOS",
  "ATRIBUTO",
  "ETIQUETAS",
  "ETIQUETA",
  "VALOR",
  "IGUAL",
  "COMILLA",
  "DIAGONAL",
  "NUEVO_SITIO_WEB",
  "BORRAR_SITIO_WEB",
  "NUEVA_PAGINA",
  "BORRAR_PAGINA",
  "MODIFICAR_PAGINA",
  "AGREGAR_COMPONENTE",
  "BORRAR_COMPONENTE",
  "MODIFICAR_COMPONENTE",
  "ID",
  "USUARIO_CREACION",
  "FECHA_CREACION",
  "FECHA_MODIFICACION",
  "USUARIO_MODIFICACION",
  "TITULO",
  "SITIO",
  "PAGINA",
  "CLASE",
  "ALINEACION",
  "TEXTO",
  "COLOR",
  "ORIGEN",
  "ALTURA",
  "ANCHO",
  "PADRE",
  "CORCHETE_ABIERTO",
  "IDD",
  "HEXADECIMAL",
  "NUMEROS",
  "PIPE",
  "DERECHA",
  "IZQUIERDA",
  "CENTRAR",
  "JUSTIFICAR",
  "PARRAFO",
  "IMAGEN",
  "VIDEO",
  "MENU",
  "URL",
  "CORCHETE_CERRADO",
  "FECHA"
  };
}

