
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym2 {
  /* terminals */
  public static final int FIN_TITULO = 19;
  public static final int INICIO_USUARIO_MODIFICACION = 12;
  public static final int IDD = 30;
  public static final int INICIO_PAGINA = 14;
  public static final int INICIO_TITULO = 18;
  public static final int INICIO_FECHA_CREACION = 8;
  public static final int INICIO_ID = 4;
  public static final int INICIO_SITIO = 2;
  public static final int FIN_FECHA_CREACION = 9;
  public static final int INICIO_ETIQUETA = 24;
  public static final int FIN_PADRE = 21;
  public static final int FIN_USUARIO_CREACION = 7;
  public static final int FIN_COMPONENTE = 27;
  public static final int FIN_LINK = 17;
  public static final int INICIO_LINK = 16;
  public static final int FIN_ETIQUETAS = 23;
  public static final int INICIO_ETIQUETAS = 22;
  public static final int FIN_FECHA_MODIFICACION = 11;
  public static final int FIN_ID = 5;
  public static final int INICIO_PADRE = 20;
  public static final int EOF = 0;
  public static final int FIN_CLASE = 29;
  public static final int FIN_PAGINA_WEB = 34;
  public static final int FIN_SITIO_WEB = 32;
  public static final int INICIO_SITIO_WEB = 31;
  public static final int error = 1;
  public static final int INICIO_COMPONENTE = 26;
  public static final int FIN_USUARIO_MODIFICACION = 13;
  public static final int INICIO_CLASE = 28;
  public static final int FIN_SITIO = 3;
  public static final int INICIO_PAGINA_WEB = 33;
  public static final int INICIO_USUARIO_CREACION = 6;
  public static final int INICIO_FECHA_MODIFICACION = 10;
  public static final int FIN_ETIQUETA = 25;
  public static final int FIN_PAGINA = 15;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INICIO_SITIO",
  "FIN_SITIO",
  "INICIO_ID",
  "FIN_ID",
  "INICIO_USUARIO_CREACION",
  "FIN_USUARIO_CREACION",
  "INICIO_FECHA_CREACION",
  "FIN_FECHA_CREACION",
  "INICIO_FECHA_MODIFICACION",
  "FIN_FECHA_MODIFICACION",
  "INICIO_USUARIO_MODIFICACION",
  "FIN_USUARIO_MODIFICACION",
  "INICIO_PAGINA",
  "FIN_PAGINA",
  "INICIO_LINK",
  "FIN_LINK",
  "INICIO_TITULO",
  "FIN_TITULO",
  "INICIO_PADRE",
  "FIN_PADRE",
  "INICIO_ETIQUETAS",
  "FIN_ETIQUETAS",
  "INICIO_ETIQUETA",
  "FIN_ETIQUETA",
  "INICIO_COMPONENTE",
  "FIN_COMPONENTE",
  "INICIO_CLASE",
  "FIN_CLASE",
  "IDD",
  "INICIO_SITIO_WEB",
  "FIN_SITIO_WEB",
  "INICIO_PAGINA_WEB",
  "FIN_PAGINA_WEB"
  };
}

